-- MySQL Script generated by MySQL Workbench
-- Sat Aug 12 15:31:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Loesungen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Loesungen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Loesungen` (
  `idLoesungen` INT NOT NULL AUTO_INCREMENT,
  `LoesungName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idLoesungen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auswahl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Auswahl` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Auswahl` (
  `idAuswahl` INT NOT NULL AUTO_INCREMENT,
  `idLoesungen_FK` INT NOT NULL COMMENT 'foreign key',
  `AuswahlName` VARCHAR(255) NOT NULL,
  `AuswahlBeschreibung` VARCHAR(2000) NULL,
  `AuswahlProdukt` VARCHAR(2000) NOT NULL,
  `AuswahlPreis` DECIMAL(7,2) NOT NULL,
  `AuswahlInkl` INT NULL,
  `AuswahlInstVorbe` DECIMAL(7,2) NULL,
  `AuswahlInstVorOrt` DECIMAL(7,2) NULL,
  PRIMARY KEY (`idAuswahl`),
  INDEX `idLoesungen_FK_idx` (`idLoesungen_FK` ASC),
  CONSTRAINT `idLoesungen_FK`
    FOREIGN KEY (`idLoesungen_FK`)
    REFERENCES `mydb`.`Loesungen` (`idLoesungen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
